language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: EalQ9iDxEuJo88qDAlOK55gQs73cl3cSN1Z96/Lo6cNJ0ug/F6ua19oqZ4MapudjGLpLdLay5Hsws2L/pop9FmZ/LTJm5iA8uw8OF5WFfavtcEXODJUuXiCdJNFrvubTV5Gpz9TmSNiiu1TMrSHxGE8r4apug2AvXPmY/O42OsrDwBMsoXgUe2c6hREEDrdXKybVHrBerHZHh+iJ7DUihzW+gzhC014k9wkkOR71Yo67SgOUPsW+8UcyFXD57eVmu7F3Y6KhA3Oh7a6w95UczRMCiq5Ig7bYhYtkpE6r72sDGZ/C4VL8ZRkuZTMl4EWXL2DAd2Nr1p+nITIEVfk14AufVvx6/YJQT25O3XYFm2z6ghFEr+wMWLTVIalZrqpUg4kV5HGu8cfNK50f1MlIzSpdsomzjIV8qmXkyC8WzNrHuFU3WNipO1PW5SvDso0C2PkpvLeHv1fCdnU3LfJMAzJkqZ43UayEkyMnNPWiITBIOwdxG4PmT22S7XIXOoiorDT7QGwWsC7K39dJdcRsWJYRO17mJ2Cn/AAiNAGu9o0lM/dCiOFJsQjrUv9J5M7wjKs/FT9YA2MzJt+PmAdvP7UVxaV6ByPGN9PGMUts4JO516KfSiGV4rhCWhZwPrKyrZg9JrTx3zv7X45pRY4bcyXUG5V/DLXVomGNYj2cVlU=
  app: cryptic-basin-76921
  on:
    repo: dab80/marvel
